[package]
name = "taskflow-state"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
taskflow-contracts = { path = "../taskflow-contracts" }
taskflow-core = { path = "../taskflow-core" }
thiserror.workspace = true

[dev-dependencies]
