[package]
name = "vida-contracts"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
garde = { version = "0.23.0", features = ["derive"] }
schemars = { version = "1.2.1", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
serde_path_to_error = "0.1.20"
serde_with = "3.21.0"
typed-builder = "0.23.2"
