[package]
name = "taskflow-state-redb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
redb.workspace = true
serde = { workspace = true }
serde_json.workspace = true
taskflow-contracts = { path = "../taskflow-contracts" }
taskflow-state = { path = "../taskflow-state" }
taskflow-state-fs = { path = "../taskflow-state-fs" }

[dev-dependencies]
taskflow-core = { path = "../taskflow-core" }
tempfile = "3.27.0"
vida-test-support = { path = "../vida-test-support" }
